### ISSUE TITLE
WatchLater  should be mapped by default to WL

### ISSUE THREAD

**Issue by cas--** [jdf76/plugin.video.youtube#199]
There seems to be some misinformation about Watch Later and Watch History. The lists have not been deprecated, just the specific way to access them in [`channels`](https://developers.google.com/youtube/v3/docs/channels/) and the API specifies that they are now under playlists.

https://developers.google.com/youtube/v3/guides/implementation/playlists

> Note that the v2 API provided separate feeds for a channel's favorite videos, watch history, and watch later playlist. The v3 API uses playlists and playlist items to represent all of these concepts.

They are not deprecated at all. It was simply properties that made them separate that have been deprecated and the ids of WL and HL are returned to denote that.

If users do want to add/remove from the list then keep the custom option but currently, the Watch Later does not work unless you add `WL` to the custom id property.

**Comment by anxdpanic** [comment]
v2 is done, and in v3 they are no longer functional as explained in the forum. I think you misundertand the documentation, watch later and history playlists were changed to WL and HL and also return empty. This still working is a leftover on YouTube's part and is only partially functional, the empty response can be confirmed by trying to use HL(for history), for WL it's only a matter of time. I have looked into this more than once over the last year, it's not like I don't want support for watch later.

The partially functional WL you are wanting as default just increases support requests because 'I can't add to watch later' or 'Auto-remove from watch later doesn't work' etc. It's easier to educate using WL or custom playlists, than adding all the support requests for a deprecated and partially working feature. 

If anything maybe we can get this added to the faq.

**Comment by anxdpanic** [comment]
https://developers.google.com/youtube/v3...on_history
September 15, 2016

In addition, requests to retrieve playlist details (playlists.list) or playlist items (playlistItems.list) for a channel's watch history or watch later playlist **now return empty lists.** This behavior is true for the new values, **HL and WL**, as well as for any watch history or watch later playlist IDs that your API Client may have already stored.

**Comment by anxdpanic** [comment]
I'll double check everything again hopefully tomorrow. I'll be happy to be wrong.

**Comment by anxdpanic** [comment]
I apologize for being terse, this is at least the 15th time I've revisted this with the same result. 

Was able to double check, and it's the same. This is what is returned by channel.list and what we already do. And again the function of HL and WL is as stated in my quote. HL = Empty, WL = Not empty yet, and no other functions available to them.

` 
"relatedPlaylists": {
     "likes": "LL1W1YsgV5vNDMLdyHaF1BpQ",
     "favorites": "FL1W1YsgV5vNDMLdyHaE8BpQ",
     "uploads": "UU1W1YsgV5vNDMLdyHbF8BpQ",
     "watchHistory": "HL",
     "watchLater": "WL"
}
`

**Comment by cas--** [comment]
I understand, and thanks for confirming what I am seeing. I could not find a concise resource as to what has happened and there does seem to be some vague changes to the API without clarification on why and replacement solution. I will see if there are any google issue tickets for this as this doesn't make any sense since there are many youtube apps and they would all break with this change.

My main point was that while `WL` still works it should still be included while keeping the custom option. For me, I am not bothered by removing or adding items, I can do this from other places. Is there not a compromise to be made whereby if a user attempts to add an item and it fails you notify them to use custom lists? Or perhaps mark the Watchlist as read-only or something similar.

As an aside, the HL seems to now be a feed in the youtube url not a playlist so that explains the lack of content.

**Comment by cas--** [comment]
So this is a bit of a turn up while looking at the requests on youtube.com with the firefox dev kit I stumbled across the playlist id for my WL playlist... I plugged the value into the plugin and I can add and remove items as per other lists! Unfortunately, I don't know exactly what link I clicked that contained the params/response details so cannot replicate it and help other users out currently :/

I still maintain that `WL` is not going to removed, the parameter in api that returns `WL` maybe but not `WL` because it is a cloak use by youtube for the real playlist id that obviously does still exist and being able to at least see the items on your watchlist is better than a custom one. The remove option for watchlater playlist can have a popup saying that this feature is not available due to blocked by youtube, or something.

**Comment by anxdpanic** [comment]
While I won't support WL directly. I have found a way to get the real playlist id, and am in the process of adding it.

**Comment by anxdpanic** [comment]
see ~alpha10 
https://github.com/jdf76/plugin.video.youtube/releases/tag/5.5.0-alpha

**Comment by anxdpanic** [comment]
Turns out the playlist id is a moving target, and not seeing an identifier (other than titles which change based on language so that's not usable.) Was able to work around this in #204 by comparing samples of playlists. Not a huge fan of the workaround but should work for now, and getting the playlist id will break if WL stops returning. 
Will bump alpha later today/tomorrow.
