### ISSUE TITLE
Question: Ad Blocker, Tracking & History

### ISSUE THREAD

**Issue by trymeouteh** [jdf76/plugin.video.youtube#704]
I had 3 question on the YouTube addon for Kodi

1. Does this addon play any YouTube ads and blocks all ads?
2. Does this addon block the cookies and trackers that YouTube and Google like to deploy
3. I do not sign into YouTube, does this addon save my search and watch history?

**Comment by Twilight0** [comment]
1) It does because there is no practical reason to implement the feature, not to mention the complexity of reporting back to Google the ad playback.
2) Cookies are not used anyway, only api keys are. So yes Google does track their usage.
3) AFAIK youtube addon is now capable of saving history locally. Haven't really used recent versions to know for sure.

**Comment by trymeouteh** [comment]
So YouTube Kodi addon does block ads?

How does Google track usage using API keys? Is the tracking only done if your logged into a Google account?

**Comment by Twilight0** [comment]
They are not actively blocked. Its because youtube addon with its python code doesn't load it. Simple as that.
Regarding API keys, google this information.
