### ISSUE TITLE
Premiere exits after 5 seconds

### ISSUE THREAD

**Issue by atatdotdot** [jdf76/plugin.video.youtube#773]
Tried to watch my church's virtual service this morning, which was pre-recorded and uploaded in advance, but scheduled to be released and streamed as-live at a specific time - I believe a YouTube refers to this as a Premiere.

Worked fine on YouTube app on Android, but on Kodi, I got the current audio and a still of the first frame for five seconds, and then the stream quits.

Video works fine after the premiere has ended.

**Comment by jpfox156** [comment]
I can confirm the same. The youtube addon errors on a Youtube Premiere video stream after near-exactly 5 seconds. The error message from Kodi's logs is below. 

From what I can make of it, it appears to be a python type error: "string indices must be integers, not str".

Note the impact is the same as [https://github.com/Kolifanes/plugin.video.youtube/issues/112](url) : `ERROR: Playlist Player: skipping unplayable item: 0, path`. I've tried adding the advancedsettings.xml as recommended in that issue with no impact - the error still occurs after 5 seconds exactly. either I haven't implemented that fix correctly, or it is unrelated. 

Stack trace from error log below:

`NOTICE: [plugin.video.youtube] Running: YouTube (6.7.0) on Leia (Kodi-18.2) with Python 2.7.15
		Path: /play/
		Params: {'video_id': 'Tynqnm579xU'}
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
	 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
	Error Type: <type 'exceptions.TypeError'>
	Error Contents: string indices must be integers, not str
	Traceback (most recent call last):
	  File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
		runner.run(__provider__)
	  File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
		__RUNNER__.run(provider, context)
	  File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
		results = provider.navigate(context)
	  File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 100, in navigate
		result = method(context, re_match)
	  File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
		return func(*args, **kwargs)
	  File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 750, in on_play
		return yt_play.play_video(self, context)
	  File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
		video_streams = client.get_video_streams(context, video_id)
	  File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 96, in get_video_streams
		video_streams = video_info.load_stream_infos(video_id, player_config, cookies)
	  File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 505, in load_stream_infos
		return self._method_get_video_info(video_id, player_config, cookies)
	  File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 929, in _method_get_video_info
		cipher)
	  File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1250, in generate_mpd
		discarded_streams.append(get_discarded_audio(mime, i, data[mime][i], 'no init or index'))
	  File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1061, in get_discarded_audio
		_discarded_stream['audio']['codec'] = str(stream['codecs'])
	TypeError: string indices must be integers, not str
	-->End of Python script error report<--
ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=Tynqnm579xU]
`

**Comment by jpfox156** [comment]
Looking at this a bit closer. The cause of the error message is line 1250 of ./resources/lib/youtube_plugin/youtube/helper/video_info.py

This instance of the call to `get_discarded_audio` (defined on line 1065 of the same file) is missing the first parameter 'fmt'.

Lines 1429-1431 provides a template of how this function should be called, where 'fmt' is populated by `self.FORMAT.get(i, {})`

I've copied this into my version of the addon running on Kodi... Now need to wait for a 'Premiere' video to trial it on... lucky Good Friday is around the corner. 

While on the surface, this appears to be a syntax issue. Given it is only encountered on (certain??) Premiere videos, it's likely that there is something more broadly wrong with the parsing of the video stream.

**Comment by jpfox156** [comment]
Ok, so although the syntax issue above is relevant, it doesn't solve the issue because the YouTube Premiere videos contain a `dashManifestUrl`, rather than statically set `initRange` and `indexRange`. This confuses the `generate_mpd` method in video_info.py, which throws out all video streams. 

Even overriding  `generate_mpd` to use the `dashManifestUrl` rather than creating a local static mpd doesn't seem to help with the 'live' nature of YouTube Premiere videos - the video feed cuts off after 15 seconds. 

It appears the easiest way to get YouTube Premiere videos running is to force the video use the HLS manifest - ie, treat it as a 'live feed'. To do this, adjust the switch on line 957 of ./resources/lib/youtube_plugin/youtube/helper/video_info.py from: 
`if is_live:`
to:
`if live_url:`

I'll see if I can create a pull request reflecting this change and correct the syntax issue identified earlier.

**Comment by jpfox156** [comment]
A final issue found during our Easter Sunday service. Premiere Videos can contain one or more text (captions) streams. These must be discarded by `generate_mpd` as non-video (audio) streams. However text streams don't contain a bitrate field, and subsequently fail on line 1069 in get_discarded_audio with a NoneType to int conversion. 

Simplest fix is to ensure that the bandwith property is always set to a value, defaulting to 0 rather than NoneType. This can be corrected on line 1207 with:

`data[mime][i]['bandwidth'] = stream_map.get('bitrate', 0)`

**Comment by anxdpanic** [comment]
Included in beta1, https://github.com/jdf76/plugin.video.youtube/releases/tag/6.7.1-dev
