### ISSUE TITLE
buffer problems in nearly each video 

### ISSUE THREAD

**Issue by damnms** [jdf76/plugin.video.youtube#883]
hi, first of all: thanks for that great addon. 
it was working for a long time now but since a couple of weeks i noticed that nearly every video i start i get heavy buffering.
when i watch the same video from my workstation (same router/connection), it works like a charm. 
when i restart those videos 3-4 times in the kodi addon, then somehow it starts to work. 
any idea what i could do to workaround that, except restarting the videos?

**Comment by boucchar** [comment]
Hi, same thing here. I am on Kodi 18.7 with YouTube Addon 6.8.17
Not sure is addon related because i launch video with yatse Kodi helper ans i get the same buffering. 
As Damnmn said, video work great on YouTube Android app on the same Network...

**Comment by jmh2002** [comment]
You YouTube addon version is now out of date. To solve your problems please update to the latest Alpha 6 version from here: https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev

If you need help chosing which version to use, or if you wish to add other Repos for the YouTube addon (eg: the Testing Repo for Alpha versions)  please see the following post in the Official Kodi YouTube support thread here: https://forum.kodi.tv/showthread.php?tid=356934&pid=3064138#pid3064138

Please note that since the Alpha 3 version you will be required to login again - twice.
(https://forum.kodi.tv/showthread.php?tid=356934&pid=3065230#pid3065230)

**Comment by damnms** [comment]
@jmh2002 can you tell me whats the difference between "official" and "unofficial" ? i did not find any useful information about that... would maybe make sense to add that information in some wiki on the kodi yt addon page or so...

**Comment by jmh2002** [comment]
@damnms Did you click on any of the links in my previous post? The second link clearly explains this, and yes the information is stated in various locations.

**Comment by damnms** [comment]
thanks, no i did not click the second or 3rd link, only the first one and updated the addon.
thanks, i clicked the second link, got the information (i would still publish that in some readme.md or so) and will go with your repo in future, thanks for your effort!
